### ISSUE TITLE
Preview does not open

### ISSUE THREAD

**Issue by nicodebo** [euclio/vim-markdown-composer#17]
hi,
I'm using `NVIM 0.1.5-dev`, `rustc 1.10.0 (cfcb716cf 2016-07-03)`, `Python 3.5.1+
` and `cargo 0.11.0-nightly (259324c 2016-05-20)`. The vim-markdown-composer plugin as been installed as shown in the installation section of the README.md.

When I open a markdown file, the preview does not open.
I can start the server manually with `:ComposerStart` command. Then,   `:ComposerPort` successfully return a port number.
But when I launch `:ComposerOpen` the following error is returned :
> error caught in async handler '/home/debz/.config/nvim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer:command:ComposerOpen []'                                                                                   
Traceback (most recent call last):                                                                               
  File "/home/debz/.config/nvim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer/__init__.py", line 58, in composer_open                                                                                           
    self.open_browser()                                                                                          
  File "/home/debz/.config/nvim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer/__init__.py", line 49, in open_browser                                                                                            
    self.client.send(msg)                                                                                        
AttributeError: 'NoneType' object has no attribute 'send'

On a side note, the documentation mention `:ComposerPreview` command but according to nvim, this is an unknown command. In addition I have `:ComposerUpdate` command which is not mentioned in the documentation.

**Comment by euclio** [comment]
Thanks for the report. Should be fixed.
